name: tencendur
channels:
- defaults
dependencies:
- python=3.5
- pip
- numpy=1.15.1
- matplotlib=3.0.0
- pip:
  - opencv-contrib-python==3.4.3.18
  - jupyter
  - tensorflow==1.11.0
  - scipy
  - scikit-image
